# Generated by Django 6.0.6 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Généré automatiquement depuis le titre', unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('fullstack', 'Full Stack'), ('frontend', 'Frontend'), ('backend', 'Backend')], default='fullstack', max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('problem', models.TextField(help_text='Le problème que ce projet résout', verbose_name='Problème')),
                ('solution', models.TextField(help_text="Comment vous l'avez résolu", verbose_name='Solution')),
                ('results', models.TextField(help_text='Un résultat par ligne. Ex: Réduction de 70% du temps de traitement', verbose_name='Résultats')),
                ('stack', models.CharField(help_text='Technologies séparées par des virgules. Ex: Next.js, Django, PostgreSQL', max_length=500, verbose_name='Stack technique')),
                ('preview_color', models.CharField(choices=[('green', 'Vert'), ('blue', 'Bleu'), ('red', 'Rouge'), ('purple', 'Violet'), ('orange', 'Orange')], default='green', max_length=10, verbose_name='Couleur preview')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image du projet')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='URL du site')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='URL GitHub')),
                ('year', models.CharField(max_length=4, verbose_name='Année')),
                ('duration', models.CharField(help_text='Ex: 6 semaines', max_length=50, verbose_name='Durée')),
                ('status', models.CharField(help_text='Ex: En production', max_length=50, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
