# Generated by Django 6.0.6 on 2026-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.TextField(help_text='Une fonctionnalité par ligne', verbose_name='Fonctionnalités')),
                ('price', models.CharField(help_text='Ex: À partir de 300k', max_length=100, verbose_name='Prix')),
                ('price_label', models.CharField(help_text='Ex: FCFA · délai 2–3 sem.', max_length=100, verbose_name='Label prix')),
                ('popular', models.BooleanField(default=False, verbose_name='Populaire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
